version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  push-image:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1e:13:63:ac:4b:db:41:64:20:3a:48:cc:87:18:61:e0"          
      - run:
          name: Build
          command: mvn -B -DskipTests -Ddocker.username=$HARBOR_USER -Ddocker.password=$HARBOR_PASSWORD clean package install

workflows:
  release:
    jobs:
      - build-and-test
      - push-image:
          requires:
            - build-and-test
          context: harbor-credentials
