version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  push-image:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: 
          name: Update image tag
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            sed -i.bak -E "s/image:\ harbor\.pintobean\.xyz\/command-runner\/command-runner([:][0-9]\.[0-9]+\.[0-9]+)?/image:\ harbor\.pintobean\.xyz\/kickstarter\/command-runner:$TAG/" deploy/deployment.yaml
      - run:
          name: Update version property
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            sed -i.bak -E "s/build.version=([0-9]\.[0-9]+\.[0-9]+)/build.version=$TAG/" src/main/resources/application.properties            
      - add_ssh_keys:
          fingerprints:
            - "1e:13:63:ac:4b:db:41:64:20:3a:48:cc:87:18:61:e0"          
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - setup_remote_docker:
          name: Setup Docker environment
          docker_layer_caching: false
      - run: 
          name: Create and push image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t harbor.pintobean.xyz/command-runner/command-runner:$TAG .
            echo $HARBOR_PASSWORD | docker login harbor.pintobean.xyz -u $HARBOR_USER --password-stdin
            docker push harbor.pintobean.xyz/command-runner/command-runner:$TAG
      - run:
          name: Push image tag
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            git config user.email "bjimerson@gmail.com"
            git config user.name "CircleCI Job"
            git checkout main
            git commit --allow-empty -am "Update image tag from CircleCI to $TAG [skip ci]"
            git push origin main
workflows:
  release:
    jobs:
      - build-and-test
      - push-image:
          requires:
            - build-and-test
          context: harbor-credentials
